const i18Obj = {
    'en': {
        'Just': 'Just dance',
        'Rides': 'Rides',
        'Service': 'Service',
        'StartNow': 'Start now',
        'LogOut': 'Log Out',
        'YourFuture': 'Your future',
        'IsElectric': 'is electric',
        'GetYourOwn': 'Get your own ebike or emoped',
        'FlexibleSubscription': 'with our flexible subscription',
        'HowItWorks': 'How it works',
        'PickCity': '1. Pick your city',
        'ChooseRide': '2. Choose your ride',
        'Delivery': '3. Delivery to your door',
        'RideFreely': '4. Ride freely',
        'MoveYourWay': 'Move your way',
        'ChooseRideThatSuits': 'Choose the electric ride that suits your lifestyle.',
        'From59': 'From €59 39€ / mo',
        'WinterOffer': 'Winter offer',
        'DanceOneStep': 'Dance One Step',
        'Ebike': 'Ebike',
        'DanceOne': 'Dance One',
        'DanceMoped': 'Dance Moped',
        'Emoped': 'Emoped',
        'SeeDetails':'See details',
        'JustRide': 'Just ride—we’ll take care of the rest',
        'LocalConcierge': 'Your local Concierge Team will repair or replace your ride within 24 hours—all included with your subscription.',
        'YourCity': 'Your city is our city',
        'AvailableIn5Cities': 'Our rides are available in 5 European cities — and counting.',
        'WantToSeeDance': 'Want to see Dance in your city?',
        'WantToKnowMore': 'Want to know more?',
        'WhereWeLocated': '+ Where we located',
        'HowDoICharge': '+ How do i charge my dance eride?',
        'WhatAccessories': '+ What accessories can I use with my ebike and emoped?',
        'HowDoRepairsWork': '+ How do repairs work?',
        'CanITestRide': '+ Can I test the ride before buying?',
        'HowDoICancel': '+ How do I cancel my membership?',
        'WhatIfStolen': '+ What happens if my vehicle gets stolen?',
        'WhatMembersSay': 'What our members say',
        'LunaReview': 'It\'s super efficient, no sweat, very stable and I get everywhere faster.',
        'LunaLocation': 'Luna, Berlin',
        'JamesReview': 'My Dance bike just makes my commute light and fun.',
        'JamesLocation': 'James, Berlin',
        'TravisReview': 'I don’t have to worry anymore about my old bike breaking down.',
        'TravisLocation': 'Travis, Hamburg',
        'StayUpToSpeed': 'Stay up to speed',
        'SignUpToGetOffers': 'Sign up to get the latest Dance offers, updates, and tips straight to your inbox.',
        'YourEmail': 'your@email.de',
        'DataCollectionInfo': 'By checking this box, you allow Dance to collect data relating to the Dance newsletter, including whether it has been opened and clicked through. For more information.',
        'Menu': 'Menu',
        'Concierge': 'Concierge',
        'ForBusiness': 'For Business',
        'Products': 'Products',
        'Ebikes': 'Ebikes',
        'Moped': 'Moped',
        'Company': 'Company',
        'About': 'About',
        'Blog': 'Blog',
        'Press': 'Press',
        'FAQ': 'FAQ',
        'Jobs': 'Jobs',
        'Legal': 'Legal',
        'Privacy': 'Privacy',
        'Imprint': 'Imprint',
        'Admin' :'Welcome,Administrator',
        'CancelSubscription': 'Cancel subscription'
    },
    'ru': {
        'Just': 'Просто танцуй',
        'Rides': 'Прогулки',
        'Service': 'Сервис',
        'StartNow': 'Начать сейчас',
        'LogOut': 'Выйти',
        'YourFuture': 'Ваше будущее',
        'IsElectric': 'электрика',
        'GetYourOwn': 'Получите свой собственный электровелосипед или электроскутер',
        'FlexibleSubscription': 'с нашей гибкой подпиской',
        'HowItWorks': 'Как это работает',
        'PickCity': '1. Выберите ваш город',
        'ChooseRide': '2. Выберите вашу поездку',
        'Delivery': '3. Доставка до вашей двери',
        'RideFreely': '4. Катайтесь свободно',
        'MoveYourWay': 'Двигайтесь по-своему',
        'ChooseRideThatSuits': 'Выберите электрическую поездку, которая подходит вашему образу жизни.',
        'From59': 'От 59€ 39€ / мес',
        'WinterOffer': 'Зимнее предложение',
        'DanceOneStep': 'Dance One Step',
        'Ebike': 'Электровелосипед',
        'SeeDetails':'Детали',
        'DanceOne': 'Dance One',
        'DanceMoped': 'Dance Moped',
        'Emoped': 'Электроскутер',
        'JustRide': 'Просто катайтесь — мы позаботимся обо всем остальном',
        'LocalConcierge': 'Ваша местная команда консьержей отремонтирует или заменит вашу поездку в течение 24 часов — все включено в вашу подписку.',
        'YourCity': 'Ваш город — наш город',
        'AvailableIn5Cities': 'Наши поездки доступны в 5 европейских городах — и их количество растет.',
        'WantToSeeDance': 'Хотите увидеть Dance в вашем городе?',
        'WantToKnowMore': 'Хотите узнать больше?',
        'WhereWeLocated': '+ Где мы находимся',
        'HowDoICharge': '+ Как заряжать мой электропоезд Dance?',
        'WhatAccessories': '+ Какие аксессуары можно использовать с моим электровелосипедом и электроскутером?',
        'HowDoRepairsWork': '+ Как работают ремонты?',
        'CanITestRide': '+ Могу ли я протестировать поездку перед покупкой?',
        'HowDoICancel': '+ Как я могу отменить свою подписку?',
        'WhatIfStolen': '+ Что делать, если мой транспорт украден?',
        'WhatMembersSay': 'Что говорят наши члены',
        'LunaReview': 'Это очень эффективно, без пота, очень стабильно, и я добираюсь везде быстрее.',
        'LunaLocation': 'Луна, Берлин',
        'JamesReview': 'Мой велосипед Dance делает мой путь на работу легким и веселым.',
        'JamesLocation': 'Джеймс, Берлин',
        'TravisReview': 'Я больше не беспокоюсь о том, что мой старый велосипед сломается.',
        'TravisLocation': 'Трэвис, Гамбург',
        'StayUpToSpeed': 'Будьте в курсе',
        'SignUpToGetOffers': 'Подпишитесь, чтобы получать последние предложения, обновления и советы Dance прямо на вашу почту.',
        'YourEmail': 'ваш@email.de',
        'DataCollectionInfo': 'Поставив галочку, вы разрешаете Dance собирать данные, относящиеся к рассылке Dance, включая информацию о том, была ли она открыта и прочитана. Для получения дополнительной информации.',
        'Menu': 'Меню',
        'Concierge': 'Консьерж',
        'ForBusiness': 'Для бизнеса',
        'Products': 'Продукты',
        'Ebikes': 'Электровелосипеды',
        'Moped': 'Скутеры',
        'Company': 'Компания',
        'About': 'О нас',
        'Blog': 'Блог',
        'Press': 'Пресса',
        'FAQ': 'Часто задаваемые вопросы',
        'Jobs': 'Работа',
        'Legal': 'Юридическая информация',
        'Privacy': 'Конфиденциальность',
        'Imprint': 'Импрессум',
        'Admin': 'Приветствуем,Администратор',
        'CancelSubscription': 'Отмена подписки'
    }
};

function getTranslate(lang) {
    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (i18Obj[lang] && i18Obj[lang][key]) {
            element.textContent = i18Obj[lang][key];
        }
    });
}

document.querySelector('.select-language').addEventListener('click', () => {
    const currentLang = document.querySelector('.select-language p').textContent;
    const newLang = currentLang === 'en' ? 'ru' : 'en';
    document.querySelector('.select-language p').textContent = newLang;
    getTranslate(newLang);
});
